##
# Set of re-usable rules for decidim module development. 
# You are required to set the following CI/CD variables: 
# 
# - CROWDIN_PERSONAL_TOKEN: protected & masked. // API Token from crowdin
# - CROWDIN_PROJECT_ID: masked. // Project ID from crowdin
# - TRANSLATIONBOT_ID: masked. // Project Bot `mr-translation` user id (see in repo>members tab)
# - TRANSLATIONBOT_ACCESS_TOKEN: masked. // Project Token with name `mr-translations`
# - GEM_HOST_API_KEY: protected & masked. // 
stages:
  - lint
  - test
  - translate
  - publish
variables:
  POSTGRES_DB: decidim_module_rest_full_test
  POSTGRES_USER: decidim
  POSTGRES_PASSWORD: "TEST-insecure_password"

services:
  - postgres:15
  - redis:latest


.development_rules:  
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
    - if: '$CI_COMMIT_TAG'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
.publication_rules:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: manual
    - if: '$CI_COMMIT_TAG'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: manual
##
# Lint ruby code
ruby::rubocop:  
  extends: .development_rules
  image: ruby:3.2.7
  stage: lint
  script:
    - bundle
    - bundle exec rubocop .

##
# Publish the gem un ruby gem.
ruby::rubygem:
  image: ruby:3.2.7
  stage: publish
  script:
    - echo "---" > .credentials
    - |
      echo ":ci_rubygems_api_key: $GEM_HOST_API_KEY" >> .credentials
    - chmod 0600 .credentials
    - gem build decidim*.gemspec
    - gem push decidim*.gem -k ci_rubygems_api_key --config-file .credentials
  only:
    - tags
##
# Upload new translation keys to crowdin
crowdin::upload:
  stage: translate
  image: node:18.20
  script:
    - npm install -g @crowdin/cli
    - crowdin upload -T $CROWDIN_PERSONAL_TOKEN -i $CROWDIN_PROJECT_ID --no-progress
    - crowdin status -T $CROWDIN_PERSONAL_TOKEN -i $CROWDIN_PROJECT_ID --no-progress
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: manual
##
# Create a Merge request in the project with updated 
# crowndin translations.
crowdin::merge_request:
  stage: translate
  image: node:18.20
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: manual
  before_script:
    - apt-get update && apt-get install -y git
  script:
    - git config --global user.email "mr-translations"
    - git config --global user.name "$TRANSLATIONBOT_ID"
    - npm install -g @crowdin/cli
    - crowdin download -T $CROWDIN_PERSONAL_TOKEN -i $CROWDIN_PROJECT_ID --no-progress
    - crowdin status -T $CROWDIN_PERSONAL_TOKEN -i $CROWDIN_PROJECT_ID --no-progress
    - export BRANCH_NAME="i18n/$(date +%Y%m%d%H%M%S)"
    - export ORIGIN="crowndin_$(date +%Y%m%d%H%M%S)"
    - echo "add $ORIGIN=https://$TRANSLATIONBOT_ID:$TRANSLATIONBOT_ACCESS_TOKEN@git.octree.ch/$CI_PROJECT_PATH.git"
    - git remote add $ORIGIN https://$TRANSLATIONBOT_ID:$TRANSLATIONBOT_ACCESS_TOKEN@git.octree.ch/$CI_PROJECT_PATH.git
    - git checkout -b $BRANCH_NAME
    - git add config/locales
    - git commit -m "Crowdin Updates"
    - git push $ORIGIN HEAD:$BRANCH_NAME -o merge_request.create -o merge_request.target=main

##
# Execute rspec and expose a spec report
ruby::rspec:
  image: ruby:3.2.7
  stage: test
  extends: .development_rules
  variables:
    DATABASE_HOST: "postgres"
    # trunk-ignore(gitleaks/generic-api-key)
    DATABASE_PASSWORD: "TEST-insecure_password"
    DATABASE_USERNAME: "decidim"
    DISABLED_DOCKER_COMPOSE: "true"
    NODE_MAJOR: 18
    SIMPLECOV: 1
    CI: 1
  before_script:
    - bin/setup-tests
  script:
    - RAILS_ENV=test bundle exec rspec spec/models/ spec/requests/ --format progress --format RspecJunitFormatter --out rspec.xml
  artifacts:
    when: always
    paths:
      - rspec.xml
    reports:
      junit: rspec.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage/coverage.xml
# Publish decidim rest full api package
decidim-client::publish:
  image: node:18.20
  variables:
    CI: 1
  before_script:
    - apt-get update -y && apt-get install -y jq
    - cd contrib/decidim-node-client
    - corepack enable
    - yarn
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .yarn/
  script:
    - yarn build
    - touch .npmrc
    - echo "@${CI_PROJECT_ROOT_NAMESPACE}:registry=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/" >> .npmrc
    - echo "${CI_API_V4_URL#http*:}/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=\${CI_JOB_TOKEN}" >> .npmrc
    - PACKAGE_VERSION=$(jq -r '.version' package.json); 
    - npm publish --non-interactive --access=public --tag$PACKAGE_VERSION --registry=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/
  extends: .publication_rules
