inherit_gem:
  decidim-dev: rubocop-decidim.yml
inherit_from:
  - .rubocop_rswag.yml
require:
  - rubocop-rspec
Naming/FileName:
  Exclude:
    - lib/decidim-rest_full.rb  # Gem entry point; name must match gem (hyphen).

RSpec/VariableName:
    EnforcedStyle: snake_case
    AllowedPatterns:
      - '^[a-z_]+\[[a-z_]*\]\[\]$' # Allows symbols like locales[][] and filter[name_in][]
      - '^[a-z_]+\[[a-z_]*\]$' # Allows symbols like locales[] and filter[name_in]
      - 'Authorization' # Authorization header
