# Crowdin — replace api_token / project_id via CI or local env as needed.
#
base_path: .
base_url: https://api.crowdin.com
api_token: "insecure_api_token"
project_id: "project_id"

preserve_hierarchy: true

files: [
  {
    "source": "/decidim-restfull-core/config/locales/decidim_rest_full.en.yml",
    "translation": "/decidim-restfull-core/config/locales/decidim_rest_full.%two_letters_code%.yml",
  },
  {
    "source": "/decidim-restfull-blogs/config/locales/decidim_rest_full_blogs.en.yml",
    "translation": "/decidim-restfull-blogs/config/locales/decidim_rest_full_blogs.%two_letters_code%.yml",
  },
  {
    "source": "/decidim-restfull-proposals/config/locales/decidim_rest_full_proposals.en.yml",
    "translation": "/decidim-restfull-proposals/config/locales/decidim_rest_full_proposals.%two_letters_code%.yml",
  }
]
