services:
  rest_full:
    command: bash -c "sleep infinity"
    image: octree/decidim-dev:0.29
    entrypoint: ""
    volumes:
      - .:/home/module
      - bundle:/home/decidim/vendor
      - node_modules:/home/decidim/node_modules
    environment:
      - PORT=3000
      - DATABASE_HOST=rest-full-pg
      - DATABASE_USERNAME=decidim
      - DATABASE_PASSWORD=pleaseChangeMe
      - DATABASE_URL=postgresql://decidim:pleaseChangeMe@rest-full-pg:5432/decidim_module_rest_full_test_app_test
      - DEV_MODULE=decidim-rest_full
      - RAILS_ENV=development
      - DISABLED_DOCKER_COMPOSE=true # To run tests in docker
    depends_on:
      - rest-full-pg
    ports:
      - 3000:3000
    links:
      - rest-full-pg

  rest-full-pg:
    image: postgres:17
    volumes:
      - rest_full-pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=decidim_module_rest_full_test_app_test
      - POSTGRES_USER=decidim
      - POSTGRES_PASSWORD=pleaseChangeMe
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U decidim"]
      interval: 2s
      timeout: 5s
      retries: 10
      start_period: 5s

volumes:
  node_modules: {}
  bundle: {}
  rest_full-pg-data: {}
