import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Explicit sidebar: adoption / operators → integrators → developers.
 */
const sidebars: SidebarsConfig = {
  documentationSidebar: [
    {
      type: 'category',
      label: 'Overview',
      collapsed: false,
      items: ['my-home-doc', 'install', 'production-mode'],
    },
    {
      type: 'category',
      label: 'Operating the API',
      collapsed: false,
      items: [
        'user_documentation/client-api-admin',
        {
          type: 'category',
          label: 'Authentication',
          items: [
            'user_documentation/auth/client-credential-flow',
            'user_documentation/auth/user-credential-flow',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Integrator guide',
      collapsed: false,
      link: {type: 'generated-index', slug: '/integrator'},
      items: [
        'integrator/quickstart',
        'integrator/permissions-and-scopes',
        'integrator/async-and-jobs',
        'integrator/resolve-component-id',
        'integrator/errors',
        'integrator/attachments',
        'integrator/webhooks',
        'integrator/contract-changes',
        'integrator/typescript-sdk',
      ],
    },
    {
      type: 'category',
      label: 'Developer documentation',
      collapsed: false,
      items: [
        'dev/architecture',
        {
          type: 'category',
          label: 'Add an endpoint',
          link: {type: 'generated-index', slug: '/dev/add-endpoint'},
          items: [{type: 'autogenerated', dirName: 'dev/add-endpoint'}],
        },
        'dev/command-line-tools',
        'dev/update-hosts',
        'dev/api-client-cli',
      ],
    },
  ],
};

export default sidebars;
