# frozen_string_literal: true

# utilities
require_relative "definitions/link"
require_relative "definitions/translated_prop"
require_relative "definitions/array_response"
require_relative "definitions/component_type"
require_relative "definitions/filter_param"
require_relative "definitions/creation_date"
require_relative "definitions/edition_date"
require_relative "definitions/tags"

# resources definitions
require_relative "definitions/blog"
require_relative "definitions/client_credential_grant"
require_relative "definitions/component"
require_relative "definitions/error"
require_relative "definitions/health"
require_relative "definitions/introspect_data"
require_relative "definitions/item_response"
require_relative "definitions/locales_param"
require_relative "definitions/manifests"
require_relative "definitions/organization"
require_relative "definitions/password_grant"
require_relative "definitions/draft_proposal"
require_relative "definitions/proposal"
require_relative "definitions/space"
require_relative "definitions/user_extended_data"
require_relative "definitions/user"
require_relative "definitions/magic_link"
require_relative "definitions/magic_link_redirect"
